name: test

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build & install
        uses: PyO3/maturin-action@v1
        with:
          args: --release
      - uses: abatilo/actions-poetry@v2
        with: { poetry-version: 1.6 }
      - run: |
          poetry install --no-root
          make test