name: test

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

permissions: { contents: read }

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-python@v5
        with: { python-version: "${{ matrix.python-version }}" }
      - uses: astral-sh/setup-uv@v6
        with: { version: "latest" }
      - run: uv sync --extra=dev
      - uses: PyO3/maturin-action@v1
        with: { args: "--release" }
      - run: make test
